

//alert('This is a  mtm6302-exercise-1. ');
// Emoji Data 😃👾👨🏼‍💻
const EmojiData = [
  //Data of 100 Differenct Emoji and their corresponding Unicode
  { emoji: '🦁', Unicode: 'U+1F409' },
  { emoji: '🐯', Unicode: 'U+1F42F' },
  { emoji: '🐷', Unicode: 'U+1F437' },
  { emoji: '🐗', Unicode: 'U+1F417' },
  { emoji: '🐘', Unicode: 'U+1F418' },
  { emoji: '🐙', Unicode: 'U+1F419' },
  { emoji: '🐚', Unicode: 'U+1F41A' },
  { emoji: '🐛', Unicode: 'U+1F41B' },
  { emoji: '🐜', Unicode: 'U+1F41C' },
  { emoji: '🐝', Unicode: 'U+1F41D' },
  { emoji: '🐞', Unicode: 'U+1F41E' },
  { emoji: '🐟', Unicode: 'U+1F41F' },
  { emoji: '🐠', Unicode: 'U+1F420' },
  { emoji: '🐡', Unicode: 'U+1F421' },
  { emoji: '🐢', Unicode: 'U+1F422' },
  { emoji: '🐣', Unicode: 'U+1F423' },
  { emoji: '🐤', Unicode: 'U+1F424' },
  { emoji: '🐥', Unicode: 'U+1F425' },
  { emoji: '🐦', Unicode: 'U+1F426' },
  { emoji: '🐧', Unicode: 'U+1F427' },
  { emoji: '🐨', Unicode: 'U+1F428' },
  { emoji: '🐩', Unicode: 'U+1F429' },
  { emoji: '🐪', Unicode: 'U+1F42A' },
  { emoji: '🐫', Unicode: 'U+1F42B' },
  { emoji: '🐬', Unicode: 'U+1F42C' },
  { emoji: '🐭', Unicode: 'U+1F42D' },
  { emoji: '🐮', Unicode: 'U+1F42E' },
  { emoji: '🐯', Unicode: 'U+1F42F' },
  { emoji: '🐰', Unicode: 'U+1F430' },
  { emoji: '🐱', Unicode: 'U+1F431' },
  { emoji: '🐲', Unicode: 'U+1F432' },
  { emoji: '🐳', Unicode: 'U+1F433' },
  { emoji: '🐴', Unicode: 'U+1F434' },
  { emoji: '🐵', Unicode: 'U+1F435' },
  { emoji: '🐶', Unicode: 'U+1F436' },
  { emoji: '🐷', Unicode: 'U+1F437' },
  { emoji: '🐸', Unicode: 'U+1F438' },
  { emoji: '🐹', Unicode: 'U+1F439' },
  { emoji: '🐺', Unicode: 'U+1F43A' },
  { emoji: '🐻', Unicode: 'U+1F43B' },
  { emoji: '🐼', Unicode: 'U+1F43C' },
  { emoji: '🐽', Unicode: 'U+1F43D' },
  { emoji: '🐾', Unicode: 'U+1F43E' },
  { emoji: '🐿', Unicode: 'U+1F43F' },
  { emoji: '👀', Unicode: 'U+1F440' },
  { emoji: '👁', Unicode: 'U+1F441' },
  { emoji: '👂', Unicode: 'U+1F442' },
  { emoji: '👃', Unicode: 'U+1F443' },
  { emoji: '👄', Unicode: 'U+1F444' },
  { emoji: '👅', Unicode: 'U+1F445' },
  { emoji: '👆', Unicode: 'U+1F446' },
  { emoji: '👇', Unicode: 'U+1F447' },
  { emoji: '👈', Unicode: 'U+1F448' },
  { emoji: '👉', Unicode: 'U+1F449' },
  { emoji: '👊', Unicode: 'U+1F44A' },
  { emoji: '👋', Unicode: 'U+1F44B' },
  { emoji: '👌', Unicode: 'U+1F44C' },
  { emoji: '👍', Unicode: 'U+1F44D' },
  { emoji: '👎', Unicode: 'U+1F44E' },
  { emoji: '👏', Unicode: 'U+1F44F' },
  { emoji: '👐', Unicode: 'U+1F450' },
  { emoji: '👑', Unicode: 'U+1F451' },
  { emoji: '👒', Unicode: 'U+1F452' },
  { emoji: '👓', Unicode: 'U+1F453' },
  { emoji: '👔', Unicode: 'U+1F454' },
  { emoji: '👕', Unicode: 'U+1F455' },
  { emoji: '👖', Unicode: 'U+1F456' },
  { emoji: '👗', Unicode: 'U+1F457' },
  { emoji: '👘', Unicode: 'U+1F458' },
  { emoji: '👙', Unicode: 'U+1F459' },
  { emoji: '👚', Unicode: 'U+1F45A' },
  { emoji: '👛', Unicode: 'U+1F45B' },
  { emoji: '👜', Unicode: 'U+1F45C' },
  { emoji: '👝', Unicode: 'U+1F45D' },
  { emoji: '👞', Unicode: 'U+1F45E' },
  { emoji: '👟', Unicode: 'U+1F45F' },
  { emoji: '👠', Unicode: 'U+1F460' },
  { emoji: '👡', Unicode: 'U+1F461' },
  { emoji: '👢', Unicode: 'U+1F462' },
  { emoji: '👣', Unicode: 'U+1F463' },
  { emoji: '👤', Unicode: 'U+1F464' },
  { emoji: '👥', Unicode: 'U+1F465' },
  { emoji: '👦', Unicode: 'U+1F466' },
  { emoji: '👧', Unicode: 'U+1F467' },
  { emoji: '👨', Unicode: 'U+1F468' },
  { emoji: '👩', Unicode: 'U+1F469' },
  { emoji: '👪', Unicode: 'U+1F46A' },
  { emoji: '👫', Unicode: 'U+1F46B' },
  { emoji: '👬', Unicode: 'U+1F46C' },
  { emoji: '👭', Unicode: 'U+1F46D' },
  { emoji: '👮', Unicode: 'U+1F46E' },
  { emoji: '👯', Unicode: 'U+1F46F' },
  { emoji: '👰', Unicode: 'U+1F470' },
  { emoji: '👱', Unicode: 'U+1F471' },
  { emoji: '👲', Unicode: 'U+1F472' },
  { emoji: '👳', Unicode: 'U+1F473' },
  { emoji: '👴', Unicode: 'U+1F474' },
  { emoji: '👵', Unicode: 'U+1F475' },
  { emoji: '👶', Unicode: 'U+1F476' },
  { emoji: '👷', Unicode: 'U+1F477' },
  { emoji: '👸', Unicode: 'U+1F478' },
  { emoji: '👹', Unicode: 'U+1F479' },
  { emoji: '👺', Unicode: 'U+1F47A' },
  { emoji: '👻', Unicode: 'U+1F47B' },
  { emoji: '👼', Unicode: 'U+1F47C' },
  { emoji: '👽', Unicode: 'U+1F47D' },
  { emoji: '👾', Unicode: 'U+1F47E' },
  { emoji: '👿', Unicode: 'U+1F47F' },
  { emoji: '💀', Unicode: 'U+1F480' },
  { emoji: '💁', Unicode: 'U+1F481' },

];

const $list = document.getElementById('list');
for (let i = 0; i < EmojiData.length; i++) {
  $list.innerHTML += `<p>
  <span style="font-size: 5rem">${EmojiData[i].emoji}</span><br />
  <code>${EmojiData[i].Unicode}</code>
</p>`


}

console.log($list.innerHTML);